In [1]:
import numpy as np
import matplotlib as plt

In [2]:
def f(a, b): #defining the bracelet function, setting the maximum size to 100 which is the maximal theoretical size of any bracelet modulo 10
    g = np.zeros(100)
    g[0] = int(a)
    g[1] = int(b)
    i=2
    while i<100:
        g[i] = (g[i-1]+g[i-2])%10
        i+=1
    return g

def onecycle(v): #truncates the bracelet to exactly one cycle
    i=1
    w=np.zeros(100)
    w[0] = v[0]
    w[1] = v[1]
    while i>=1 and (v[i] != v[0] and v[i+1] != v[1]) or (v[i] == v[0] and v[i+1] != v[1]) or (v[i] != v[0] and v[i+1] == v[1]):
        w[i] = v[i]
        i+=1
    n=i
    x=list(w)
    del x[n:100]
    w1 = np.array(x)
    return w1


In [3]:
#<1,5>
print(f(1, 5))
print(onecycle(f(1,5)))
print(len(onecycle(f(1,5))))

[1. 5. 6. 1. 7. 8. 5. 3. 8. 1. 9. 0. 9. 9. 8. 7. 5. 2. 7. 9. 6. 5. 1. 6.
 7. 3. 0. 3. 3. 6. 9. 5. 4. 9. 3. 2. 5. 7. 2. 9. 1. 0. 1. 1. 2. 3. 5. 8.
 3. 1. 4. 5. 9. 4. 3. 7. 0. 7. 7. 4. 1. 5. 6. 1. 7. 8. 5. 3. 8. 1. 9. 0.
 9. 9. 8. 7. 5. 2. 7. 9. 6. 5. 1. 6. 7. 3. 0. 3. 3. 6. 9. 5. 4. 9. 3. 2.
 5. 7. 2. 9.]
[1. 5. 6. 1. 7. 8. 5. 3. 8. 1. 9. 0. 9. 9. 8. 7. 5. 2. 7. 9. 6. 5. 1. 6.
 7. 3. 0. 3. 3. 6. 9. 5. 4. 9. 3. 2. 5. 7. 2. 9. 1. 0. 1. 1. 2. 3. 5. 8.
 3. 1. 4. 5. 9. 4. 3. 7. 0. 7. 7. 4.]
60


In [4]:
#<8, 9>
print(f(8, 9))
print(onecycle(f(8, 9)))
print(len(onecycle(f(8,9))))

[8. 9. 7. 6. 3. 9. 2. 1. 3. 4. 7. 1. 8. 9. 7. 6. 3. 9. 2. 1. 3. 4. 7. 1.
 8. 9. 7. 6. 3. 9. 2. 1. 3. 4. 7. 1. 8. 9. 7. 6. 3. 9. 2. 1. 3. 4. 7. 1.
 8. 9. 7. 6. 3. 9. 2. 1. 3. 4. 7. 1. 8. 9. 7. 6. 3. 9. 2. 1. 3. 4. 7. 1.
 8. 9. 7. 6. 3. 9. 2. 1. 3. 4. 7. 1. 8. 9. 7. 6. 3. 9. 2. 1. 3. 4. 7. 1.
 8. 9. 7. 6.]
[8. 9. 7. 6. 3. 9. 2. 1. 3. 4. 7. 1.]
12


In [5]:
#<0,5>
print(f(0, 5))
print(onecycle(f(0, 5)))
print(len(onecycle(f(0,5))))

[0. 5. 5. 0. 5. 5. 0. 5. 5. 0. 5. 5. 0. 5. 5. 0. 5. 5. 0. 5. 5. 0. 5. 5.
 0. 5. 5. 0. 5. 5. 0. 5. 5. 0. 5. 5. 0. 5. 5. 0. 5. 5. 0. 5. 5. 0. 5. 5.
 0. 5. 5. 0. 5. 5. 0. 5. 5. 0. 5. 5. 0. 5. 5. 0. 5. 5. 0. 5. 5. 0. 5. 5.
 0. 5. 5. 0. 5. 5. 0. 5. 5. 0. 5. 5. 0. 5. 5. 0. 5. 5. 0. 5. 5. 0. 5. 5.
 0. 5. 5. 0.]
[0. 5. 5.]
3


In [6]:
#<0, 4>
print(f(0, 4))
print(onecycle(f(0, 4)))
print(len(onecycle(f(0,4))))

[0. 4. 4. 8. 2. 0. 2. 2. 4. 6. 0. 6. 6. 2. 8. 0. 8. 8. 6. 4. 0. 4. 4. 8.
 2. 0. 2. 2. 4. 6. 0. 6. 6. 2. 8. 0. 8. 8. 6. 4. 0. 4. 4. 8. 2. 0. 2. 2.
 4. 6. 0. 6. 6. 2. 8. 0. 8. 8. 6. 4. 0. 4. 4. 8. 2. 0. 2. 2. 4. 6. 0. 6.
 6. 2. 8. 0. 8. 8. 6. 4. 0. 4. 4. 8. 2. 0. 2. 2. 4. 6. 0. 6. 6. 2. 8. 0.
 8. 8. 6. 4.]
[0. 4. 4. 8. 2. 0. 2. 2. 4. 6. 0. 6. 6. 2. 8. 0. 8. 8. 6. 4.]
20


In [7]:
#<0,0>
print(f(0, 0))
print(onecycle(f(0, 0)))
print(len(onecycle(f(0,0))))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
[0.]
1


In [8]:
#<4, 2>
print(f(4, 2))
print(onecycle(f(4, 2)))
print(len(onecycle(f(4,2))))

[4. 2. 6. 8. 4. 2. 6. 8. 4. 2. 6. 8. 4. 2. 6. 8. 4. 2. 6. 8. 4. 2. 6. 8.
 4. 2. 6. 8. 4. 2. 6. 8. 4. 2. 6. 8. 4. 2. 6. 8. 4. 2. 6. 8. 4. 2. 6. 8.
 4. 2. 6. 8. 4. 2. 6. 8. 4. 2. 6. 8. 4. 2. 6. 8. 4. 2. 6. 8. 4. 2. 6. 8.
 4. 2. 6. 8. 4. 2. 6. 8. 4. 2. 6. 8. 4. 2. 6. 8. 4. 2. 6. 8. 4. 2. 6. 8.
 4. 2. 6. 8.]
[4. 2. 6. 8.]
4


In [9]:
a=len(onecycle(f(1, 5)))
b=len(onecycle(f(8, 9)))
c=len(onecycle(f(0, 5)))
d=len(onecycle(f(0, 4)))
e=len(onecycle(f(0, 0)))
g=len(onecycle(f(4, 2)))
h=a+b+c+d+e+g
print(h)

100
